# Generated by Django 4.1.6 on 2023-02-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_status_product_published_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='product_name_again',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
    ]
