# Generated by Django 4.1.6 on 2023-02-10 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_subject_product_name_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='product_name_again',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
    ]
