# Generated by Django 4.1.6 on 2023-02-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published_status', 'Can publish Product')]},
        ),
    ]
