# Generated by Django 4.1.6 on 2023-02-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[('active', 'available'), ('inactive', 'no item')], default='active', max_length=20),
        ),
    ]
